package waktusholat

type (
	PrayTimeRequest struct {
		City      string `json:"city" binding:"required"`
		Country   string `json:"-"`
		StartDate string `json:"start_date" binding:"required"`
		EndDate   string `json:"end_date" binding:"required"`
	}

	PrayTimeResponse struct {
		Code    int                  `json:"code"`
		Status  string               `json:"status"`
		Results DataPrayTimeResponse `json:"results"`
	}

	DataPrayTimeResponse struct {
		Datetime []DateTime `json:"datetime"`
		Location Location   `json:"location"`
	}

	DateTime struct {
		Times map[string]string `json:"times"`
		Date  struct {
			Timestamp int64  `json:"timestamp"`
			Gregorian string `json:"gregorian"`
			Hijri     string `json:"hijri"`
		}
	}

	Location struct {
		City        string `json:"city"`
		Country     string `json:"country"`
		CountryCode string `json:"country_code"`
		Timezone    string `json:"timezone"`
	}

	GetCityByNameResponse struct {
		CityCode    string `json:"cityCode"`
		CityName    string `json:"cityName"`
		CountryCode string `json:"countryCode"`
		CountryName string `json:"countryName"`
	}
)

var (
	SchoolMap = map[string]int{
		"Afghanistan":                       1,
		"Afrika Selatan":                    5,
		"Albania":                           3,
		"Algeria":                           5,
		"Amerika Serikat":                   2,
		"Andorra":                           3,
		"Angola":                            5,
		"Anguilla":                          3,
		"Antartika":                         3,
		"Antigua dan Barbuda":               3,
		"Arab Saudi":                        4,
		"Argentina":                         3,
		"Armenia":                           3,
		"Aruba":                             3,
		"Australia":                         3,
		"Austria":                           3,
		"Azerbaijan":                        3,
		"Bahama":                            3,
		"Bahrain":                           4,
		"Bangladesh":                        1,
		"Barbados":                          3,
		"Belanda":                           3,
		"Belarus":                           3,
		"Belgia":                            3,
		"Belize":                            3,
		"Benin":                             5,
		"Bermuda":                           3,
		"Bhutan":                            3,
		"Bolivia":                           3,
		"Bonaire, Saint Eustatius and Saba": 3,
		"Bosnia dan Herzegowina":            3,
		"Botswana":                          5,
		"Brasil":                            3,
		"Brunei Darussalam":                 3,
		"Bulgaria":                          3,
		"Burkina Faso":                      5,
		"Burundi":                           5,
		"Chad":                              5,
		"Chili":                             3,
		"China":                             3,
		"Côte d'Ivoire":                     5,
		"Country of Curaçao":                3,
		"Denmark":                           3,
		"Djibouti":                          5,
		"Dominika":                          3,
		"Ekuador":                           3,
		"El Salvador":                       3,
		"Eritrea":                           5,
		"Estonia":                           3,
		"Etiopia":                           5,
		"Fiji":                              3,
		"Filipina":                          3,
		"Finlandia":                         3,
		"Gabon":                             5,
		"Gambia":                            5,
		"Georgia":                           3,
		"Georgia Selatan dan Kepulauan Sandwich Selatan": 3,
		"Ghana":               5,
		"Gibraltar":           3,
		"Grenada":             3,
		"Guadeloupe":          3,
		"Guam":                3,
		"Guatemala":           3,
		"Guernsey":            3,
		"Guinea":              5,
		"Guinea Khatulistiwa": 5,
		"Guinea-Bissau":       5,
		"Guyana":              3,
		"Guyana Perancis":     3,
		"Haiti":               3,
		"Honduras":            3,
		"Hong Kong":           3,
		"Hongaria":            3,
		"India":               1,
		"Indonesia":           9,
		"Irak":                3,
		"Iran":                7,
		"Irlandia":            3,
		"Islandia":            3,
		"Israel":              3,
		"Italia":              3,
		"Jamaika":             3,
		"Jepang":              3,
		"Jerman":              3,
		"Jersey":              3,
		"Kaledonia Baru":      3,
		"Kamboja":             3,
		"Kamerun":             5,
		"Kanada":              2,
		"Kazakhstan":          3,
		"Kenya":               5,
		"Kepulauan Aland":     3,
		"Kepulauan Cayman":    3,
		"Kepulauan Cocos":     3,
		"Kepulauan Cook":      3,
		"Kepulauan Falkland (Kepulauan Malvinas)": 3,
		"Kepulauan Faroe":                         3,
		"Kepulauan Mariana Utara":                 3,
		"Kepulauan Marshall":                      3,
		"Kepulauan Pitcairn":                      3,
		"Kepulauan Solomon":                       3,
		"Kepulauan Turks dan Caicos":              3,
		"Kepulauan Virgin":                        3,
		"Kepulauan Virgin Inggris":                3,
		"Kerajaan Inggris":                        3,
		"Kirgistan":                               3,
		"Kiribati":                                3,
		"Kolombia":                                3,
		"Komoro":                                  5,
		"Kongo":                                   5,
		"Korea Selatan":                           3,
		"Korea Utara":                             3,
		"Kosta Rika":                              3,
		"Kroasia":                                 3,
		"Kuba":                                    3,
		"Kuwait":                                  4,
		"Laos":                                    3,
		"Latvia":                                  3,
		"Lesotho":                                 5,
		"Libanon":                                 3,
		"Liberia":                                 5,
		"Libya":                                   5,
		"Liechtenstein":                           3,
		"Lituania":                                3,
		"Luksemburg":                              3,
		"Madagaskar":                              5,
		"Makau":                                   3,
		"Makedonia":                               3,
		"Maladewa":                                3,
		"Malawi":                                  5,
		"Malaysia":                                9,
		"Mali":                                    5,
		"Malta":                                   3,
		"Maroko":                                  5,
		"Martinique":                              3,
		"Mauritania":                              5,
		"Mauritius":                               5,
		"Mayotte":                                 5,
		"Meksiko":                                 3,
		"Mesir":                                   5,
		"Mikronesia":                              3,
		"Moldova":                                 3,
		"Monako":                                  3,
		"Mongolia":                                3,
		"Montenegro":                              3,
		"Montserrat":                              3,
		"Mozambik":                                5,
		"Myanmar":                                 3,
		"Namibia":                                 5,
		"Nauru":                                   3,
		"Nepal":                                   3,
		"Niger":                                   5,
		"Nigeria":                                 5,
		"Nikaragua":                               3,
		"Niue":                                    3,
		"Norwegia":                                3,
		"Oman":                                    4,
		"Pakistan":                                1,
		"Palau":                                   3,
		"Palestina":                               3,
		"Panama":                                  3,
		"Papua Nugini":                            3,
		"Paraguay":                                3,
		"Peru":                                    3,
		"Polandia":                                3,
		"Polinesia Prancis":                       3,
		"Portugal":                                3,
		"Prancis":                                 11,
		"Puerto Riko":                             3,
		"Pulau Bouvet":                            3,
		"Pulau Heard dan Kepulauan McDonald":      3,
		"Pulau Natal":                             3,
		"Pulau Norfolk":                           3,
		"Qatar":                                   4,
		"Republic of Kosovo":                      3,
		"Republik Afrika Tengah":                  5,
		"Republik Ceko":                           3,
		"Republik Demokratik Kongo":               5,
		"Republik Dominika":                       3,
		"Reunion":                                 5,
		"Romania":                                 3,
		"Rusia":                                   3,
		"Rwanda":                                  5,
		"Sahara Barat":                            3,
		"Saint Barthelemy":                        3,
		"Saint Helena":                            5,
		"Saint Kitts dan Nevis":                   3,
		"Saint Lucia":                             3,
		"Saint Martin":                            3,
		"Saint Pierre dan Miquelon":               3,
		"Saint Vincent dan Grenadines":            3,
		"Samoa":                                   3,
		"Samoa Amerika":                           3,
		"San Marino":                              3,
		"Sao Tome dan Príncipe":                   5,
		"Selandia Baru":                           3,
		"Selatan Perancis dan Daratan Antartika":  3,
		"Senegal":                                 5,
		"Serbia":                                  3,
		"Seychelles":                              5,
		"Sierra Leone":                            5,
		"Singapura":                               10,
		"Sint Maarten":                            3,
		"Siprus":                                  3,
		"Slovakia":                                3,
		"Slovenia":                                3,
		"Somalia":                                 5,
		"South Sudan":                             5,
		"Spanyol":                                 3,
		"Sri Lanka":                               3,
		"Sudan":                                   3,
		"Suriah":                                  3,
		"Suriname":                                3,
		"Svalbard":                                3,
		"Swaziland":                               5,
		"Swedia":                                  3,
		"Swiss":                                   3,
		"Tahta Suci (Vatikan)":                    3,
		"Taiwan":                                  3,
		"Tajikistan":                              3,
		"Tanah Hijau":                             3,
		"Tanjung Verde":                           5,
		"Tanzania":                                5,
		"Teritori Inggris di Samudra Hindia":      3,
		"Thailand":                                3,
		"Timor-Leste":                             3,
		"Togo":                                    5,
		"Tokelau":                                 3,
		"Tonga":                                   3,
		"Trinidad dan Tobago":                     3,
		"Tunisia":                                 5,
		"Turki":                                   12,
		"Turkmenistan":                            3,
		"Tuvalu":                                  3,
		"Uganda":                                  5,
		"Ukraina":                                 3,
		"Uni Emirat Arab":                         4,
		"United States Minor Outlying Islands":    3,
		"Uruguay":                                 3,
		"Uzbekistan":                              3,
		"Vanuatu":                                 3,
		"Venezuela":                               3,
		"Vietnam":                                 3,
		"Wallis dan Futuna":                       3,
		"Yaman":                                   4,
		"Yordania":                                3,
		"Yunani":                                  3,
		"Zambia":                                  5,
		"Zimbabwe":                                5,
	}
)
