package waktusholat

type (
	PrayTimeRequest struct {
		City        string `json:"city" binding:"required"`
		CountryCode string `json:"-"`
		StartDate   string `json:"start_date" binding:"required"`
		EndDate     string `json:"end_date" binding:"required"`
	}

	PrayTimeResponse struct {
		Code    int                  `json:"code"`
		Status  string               `json:"status"`
		Results DataPrayTimeResponse `json:"results"`
	}

	DataPrayTimeResponse struct {
		Datetime []DateTime `json:"datetime"`
		Location Location   `json:"location"`
	}

	DateTime struct {
		Times map[string]string `json:"times"`
		Date  struct {
			Timestamp int64  `json:"timestamp"`
			Gregorian string `json:"gregorian"`
			Hijri     string `json:"hijri"`
		}
	}

	Location struct {
		City        string `json:"city"`
		Country     string `json:"country"`
		CountryCode string `json:"country_code"`
		Timezone    string `json:"timezone"`
	}

	GetCityByNameResponse struct {
		CityCode    string `json:"cityCode"`
		CityName    string `json:"cityName"`
		CountryCode string `json:"countryCode"`
		CountryName string `json:"countryName"`
	}

	School struct {
		ID      int
		Country string
		Name    string
	}
)

var (
	SchoolMap = map[string]School{
		"IM": {ID: 3, Country: "", Name: "Liga Muslim dunia"},
		"AF": {ID: 1, Country: "Afghanistan", Name: "Universitas Ilmu Keislaman Karachi"},
		"ZA": {ID: 5, Country: "Afrika Selatan", Name: "Dinas geologi Mesir"},
		"AL": {ID: 3, Country: "Albania", Name: "Liga Muslim dunia"},
		"DZ": {ID: 5, Country: "Algeria", Name: "Dinas geologi Mesir"},
		"US": {ID: 2, Country: "Amerika Serikat", Name: "Masyarakat Islam Amerika Utara"},
		"AD": {ID: 3, Country: "Andorra", Name: "Liga Muslim dunia"},
		"AO": {ID: 5, Country: "Angola", Name: "Dinas geologi Mesir"},
		"AI": {ID: 3, Country: "Anguilla", Name: "Liga Muslim dunia"},
		"AQ": {ID: 3, Country: "Antartika", Name: "Liga Muslim dunia"},
		"AG": {ID: 3, Country: "Antigua dan Barbuda", Name: "Liga Muslim dunia"},
		"SA": {ID: 4, Country: "Arab Saudi", Name: "Umm Al Qura University, Mekkah"},
		"AR": {ID: 3, Country: "Argentina", Name: "Liga Muslim dunia"},
		"AM": {ID: 3, Country: "Armenia", Name: "Liga Muslim dunia"},
		"AW": {ID: 3, Country: "Aruba", Name: "Liga Muslim dunia"},
		"AU": {ID: 3, Country: "Australia", Name: "Liga Muslim dunia"},
		"AT": {ID: 3, Country: "Austria", Name: "Liga Muslim dunia"},
		"AZ": {ID: 3, Country: "Azerbaijan", Name: "Liga Muslim dunia"},
		"BS": {ID: 3, Country: "Bahama", Name: "Liga Muslim dunia"},
		"BH": {ID: 4, Country: "Bahrain", Name: "Umm Al Qura University, Mekkah"},
		"BD": {ID: 1, Country: "Bangladesh", Name: "Universitas Ilmu Keislaman Karachi"},
		"BB": {ID: 3, Country: "Barbados", Name: "Liga Muslim dunia"},
		"NL": {ID: 3, Country: "Belanda", Name: "Liga Muslim dunia"},
		"BY": {ID: 3, Country: "Belarus", Name: "Liga Muslim dunia"},
		"BE": {ID: 3, Country: "Belgia", Name: "Liga Muslim dunia"},
		"BZ": {ID: 3, Country: "Belize", Name: "Liga Muslim dunia"},
		"BJ": {ID: 5, Country: "Benin", Name: "Dinas geologi Mesir"},
		"BM": {ID: 3, Country: "Bermuda", Name: "Liga Muslim dunia"},
		"BT": {ID: 3, Country: "Bhutan", Name: "Liga Muslim dunia"},
		"BO": {ID: 3, Country: "Bolivia", Name: "Liga Muslim dunia"},
		"BQ": {ID: 3, Country: "Bonaire, Saint Eustatius and Saba", Name: "Liga Muslim dunia"},
		"BA": {ID: 3, Country: "Bosnia dan Herzegowina", Name: "Liga Muslim dunia"},
		"BW": {ID: 5, Country: "Botswana", Name: "Dinas geologi Mesir"},
		"BR": {ID: 3, Country: "Brasil", Name: "Liga Muslim dunia"},
		"BN": {ID: 3, Country: "Brunei Darussalam", Name: "Liga Muslim dunia"},
		"BG": {ID: 3, Country: "Bulgaria", Name: "Liga Muslim dunia"},
		"BF": {ID: 5, Country: "Burkina Faso", Name: "Dinas geologi Mesir"},
		"BI": {ID: 5, Country: "Burundi", Name: "Dinas geologi Mesir"},
		"TD": {ID: 5, Country: "Chad", Name: "Dinas geologi Mesir"},
		"CL": {ID: 3, Country: "Chili", Name: "Liga Muslim dunia"},
		"CN": {ID: 3, Country: "China", Name: "Liga Muslim dunia"},
		"CI": {ID: 5, Country: "Côte d'Ivoire", Name: "Dinas geologi Mesir"},
		"CW": {ID: 3, Country: "Country of Curaçao", Name: "Liga Muslim dunia"},
		"DK": {ID: 3, Country: "Denmark", Name: "Liga Muslim dunia"},
		"DJ": {ID: 5, Country: "Djibouti", Name: "Dinas geologi Mesir"},
		"DM": {ID: 3, Country: "Dominika", Name: "Liga Muslim dunia"},
		"EC": {ID: 3, Country: "Ekuador", Name: "Liga Muslim dunia"},
		"SV": {ID: 3, Country: "El Salvador", Name: "Liga Muslim dunia"},
		"ER": {ID: 5, Country: "Eritrea", Name: "Dinas geologi Mesir"},
		"EE": {ID: 3, Country: "Estonia", Name: "Liga Muslim dunia"},
		"ET": {ID: 5, Country: "Etiopia", Name: "Dinas geologi Mesir"},
		"FJ": {ID: 3, Country: "Fiji", Name: "Liga Muslim dunia"},
		"PH": {ID: 3, Country: "Filipina", Name: "Liga Muslim dunia"},
		"FI": {ID: 3, Country: "Finlandia", Name: "Liga Muslim dunia"},
		"GA": {ID: 5, Country: "Gabon", Name: "Dinas geologi Mesir"},
		"GM": {ID: 5, Country: "Gambia", Name: "Dinas geologi Mesir"},
		"GE": {ID: 3, Country: "Georgia", Name: "Liga Muslim dunia"},
		"GS": {ID: 3, Country: "Georgia Selatan dan Kepulauan Sandwich Selatan", Name: "Liga Muslim dunia"},
		"GH": {ID: 5, Country: "Ghana", Name: "Dinas geologi Mesir"},
		"GI": {ID: 3, Country: "Gibraltar", Name: "Liga Muslim dunia"},
		"GD": {ID: 3, Country: "Grenada", Name: "Liga Muslim dunia"},
		"GP": {ID: 3, Country: "Guadeloupe", Name: "Liga Muslim dunia"},
		"GU": {ID: 3, Country: "Guam", Name: "Liga Muslim dunia"},
		"GT": {ID: 3, Country: "Guatemala", Name: "Liga Muslim dunia"},
		"GG": {ID: 3, Country: "Guernsey", Name: "Liga Muslim dunia"},
		"GN": {ID: 5, Country: "Guinea", Name: "Dinas geologi Mesir"},
		"GQ": {ID: 5, Country: "Guinea Khatulistiwa", Name: "Dinas geologi Mesir"},
		"GW": {ID: 5, Country: "Guinea-Bissau", Name: "Dinas geologi Mesir"},
		"GY": {ID: 3, Country: "Guyana", Name: "Liga Muslim dunia"},
		"GF": {ID: 3, Country: "Guyana Perancis", Name: "Liga Muslim dunia"},
		"HT": {ID: 3, Country: "Haiti", Name: "Liga Muslim dunia"},
		"HN": {ID: 3, Country: "Honduras", Name: "Liga Muslim dunia"},
		"HK": {ID: 3, Country: "Hong Kong", Name: "Liga Muslim dunia"},
		"HU": {ID: 3, Country: "Hongaria", Name: "Liga Muslim dunia"},
		"IN": {ID: 1, Country: "India", Name: "Universitas Ilmu Keislaman Karachi"},
		"ID": {ID: 9, Country: "Indonesia", Name: "Departemen kemajuan Islam, Malaysia (JAKIM)"},
		"IQ": {ID: 3, Country: "Irak", Name: "Liga Muslim dunia"},
		"IR": {ID: 7, Country: "Iran", Name: "Institut geofisika, Universitas Teheran"},
		"IE": {ID: 3, Country: "Irlandia", Name: "Liga Muslim dunia"},
		"IS": {ID: 3, Country: "Islandia", Name: "Liga Muslim dunia"},
		"IL": {ID: 3, Country: "Israel", Name: "Liga Muslim dunia"},
		"IT": {ID: 3, Country: "Italia", Name: "Liga Muslim dunia"},
		"JM": {ID: 3, Country: "Jamaika", Name: "Liga Muslim dunia"},
		"JP": {ID: 3, Country: "Jepang", Name: "Liga Muslim dunia"},
		"DE": {ID: 3, Country: "Jerman", Name: "Liga Muslim dunia"},
		"JE": {ID: 3, Country: "Jersey", Name: "Liga Muslim dunia"},
		"NC": {ID: 3, Country: "Kaledonia Baru", Name: "Liga Muslim dunia"},
		"KH": {ID: 3, Country: "Kamboja", Name: "Liga Muslim dunia"},
		"CM": {ID: 5, Country: "Kamerun", Name: "Dinas geologi Mesir"},
		"CA": {ID: 2, Country: "Kanada", Name: "Masyarakat Islam Amerika Utara"},
		"KZ": {ID: 3, Country: "Kazakhstan", Name: "Liga Muslim dunia"},
		"KE": {ID: 5, Country: "Kenya", Name: "Dinas geologi Mesir"},
		"AX": {ID: 3, Country: "Kepulauan Aland", Name: "Liga Muslim dunia"},
		"KY": {ID: 3, Country: "Kepulauan Cayman", Name: "Liga Muslim dunia"},
		"CC": {ID: 3, Country: "Kepulauan Cocos", Name: "Liga Muslim dunia"},
		"CK": {ID: 3, Country: "Kepulauan Cook", Name: "Liga Muslim dunia"},
		"FK": {ID: 3, Country: "Kepulauan Falkland (Kepulauan Malvinas)", Name: "Liga Muslim dunia"},
		"FO": {ID: 3, Country: "Kepulauan Faroe", Name: "Liga Muslim dunia"},
		"MP": {ID: 3, Country: "Kepulauan Mariana Utara", Name: "Liga Muslim dunia"},
		"MH": {ID: 3, Country: "Kepulauan Marshall", Name: "Liga Muslim dunia"},
		"PN": {ID: 3, Country: "Kepulauan Pitcairn", Name: "Liga Muslim dunia"},
		"SB": {ID: 3, Country: "Kepulauan Solomon", Name: "Liga Muslim dunia"},
		"TC": {ID: 3, Country: "Kepulauan Turks dan Caicos", Name: "Liga Muslim dunia"},
		"VI": {ID: 3, Country: "Kepulauan Virgin", Name: "Liga Muslim dunia"},
		"VG": {ID: 3, Country: "Kepulauan Virgin Inggris", Name: "Liga Muslim dunia"},
		"GB": {ID: 3, Country: "Kerajaan Inggris", Name: "Liga Muslim dunia"},
		"KG": {ID: 3, Country: "Kirgistan", Name: "Liga Muslim dunia"},
		"KI": {ID: 3, Country: "Kiribati", Name: "Liga Muslim dunia"},
		"CO": {ID: 3, Country: "Kolombia", Name: "Liga Muslim dunia"},
		"KM": {ID: 5, Country: "Komoro", Name: "Dinas geologi Mesir"},
		"CG": {ID: 5, Country: "Kongo", Name: "Dinas geologi Mesir"},
		"KR": {ID: 3, Country: "Korea Selatan", Name: "Liga Muslim dunia"},
		"KP": {ID: 3, Country: "Korea Utara", Name: "Liga Muslim dunia"},
		"CR": {ID: 3, Country: "Kosta Rika", Name: "Liga Muslim dunia"},
		"HR": {ID: 3, Country: "Kroasia", Name: "Liga Muslim dunia"},
		"CU": {ID: 3, Country: "Kuba", Name: "Liga Muslim dunia"},
		"KW": {ID: 4, Country: "Kuwait", Name: "Umm Al Qura University, Mekkah"},
		"LA": {ID: 3, Country: "Laos", Name: "Liga Muslim dunia"},
		"LV": {ID: 3, Country: "Latvia", Name: "Liga Muslim dunia"},
		"LS": {ID: 5, Country: "Lesotho", Name: "Dinas geologi Mesir"},
		"LB": {ID: 3, Country: "Libanon", Name: "Liga Muslim dunia"},
		"LR": {ID: 5, Country: "Liberia", Name: "Dinas geologi Mesir"},
		"LY": {ID: 5, Country: "Libya", Name: "Dinas geologi Mesir"},
		"LI": {ID: 3, Country: "Liechtenstein", Name: "Liga Muslim dunia"},
		"LT": {ID: 3, Country: "Lituania", Name: "Liga Muslim dunia"},
		"LU": {ID: 3, Country: "Luksemburg", Name: "Liga Muslim dunia"},
		"MG": {ID: 5, Country: "Madagaskar", Name: "Dinas geologi Mesir"},
		"MO": {ID: 3, Country: "Makau", Name: "Liga Muslim dunia"},
		"MK": {ID: 3, Country: "Makedonia", Name: "Liga Muslim dunia"},
		"MV": {ID: 3, Country: "Maladewa", Name: "Liga Muslim dunia"},
		"MW": {ID: 5, Country: "Malawi", Name: "Dinas geologi Mesir"},
		"MY": {ID: 9, Country: "Malaysia", Name: "Departemen kemajuan Islam, Malaysia (JAKIM)"},
		"ML": {ID: 5, Country: "Mali", Name: "Dinas geologi Mesir"},
		"MT": {ID: 3, Country: "Malta", Name: "Liga Muslim dunia"},
		"MA": {ID: 5, Country: "Maroko", Name: "Dinas geologi Mesir"},
		"MQ": {ID: 3, Country: "Martinique", Name: "Liga Muslim dunia"},
		"MR": {ID: 5, Country: "Mauritania", Name: "Dinas geologi Mesir"},
		"MU": {ID: 5, Country: "Mauritius", Name: "Dinas geologi Mesir"},
		"YT": {ID: 5, Country: "Mayotte", Name: "Dinas geologi Mesir"},
		"MX": {ID: 3, Country: "Meksiko", Name: "Liga Muslim dunia"},
		"EG": {ID: 5, Country: "Mesir", Name: "Dinas geologi Mesir"},
		"FM": {ID: 3, Country: "Mikronesia", Name: "Liga Muslim dunia"},
		"MD": {ID: 3, Country: "Moldova", Name: "Liga Muslim dunia"},
		"MC": {ID: 3, Country: "Monako", Name: "Liga Muslim dunia"},
		"MN": {ID: 3, Country: "Mongolia", Name: "Liga Muslim dunia"},
		"ME": {ID: 3, Country: "Montenegro", Name: "Liga Muslim dunia"},
		"MS": {ID: 3, Country: "Montserrat", Name: "Liga Muslim dunia"},
		"MZ": {ID: 5, Country: "Mozambik", Name: "Dinas geologi Mesir"},
		"MM": {ID: 3, Country: "Myanmar", Name: "Liga Muslim dunia"},
		"NA": {ID: 5, Country: "Namibia", Name: "Dinas geologi Mesir"},
		"NR": {ID: 3, Country: "Nauru", Name: "Liga Muslim dunia"},
		"NP": {ID: 3, Country: "Nepal", Name: "Liga Muslim dunia"},
		"NE": {ID: 5, Country: "Niger", Name: "Dinas geologi Mesir"},
		"NG": {ID: 5, Country: "Nigeria", Name: "Dinas geologi Mesir"},
		"NI": {ID: 3, Country: "Nikaragua", Name: "Liga Muslim dunia"},
		"NU": {ID: 3, Country: "Niue", Name: "Liga Muslim dunia"},
		"NO": {ID: 3, Country: "Norwegia", Name: "Liga Muslim dunia"},
		"OM": {ID: 4, Country: "Oman", Name: "Umm Al Qura University, Mekkah"},
		"PK": {ID: 1, Country: "Pakistan", Name: "Universitas Ilmu Keislaman Karachi"},
		"PW": {ID: 3, Country: "Palau", Name: "Liga Muslim dunia"},
		"PS": {ID: 3, Country: "Palestina", Name: "Liga Muslim dunia"},
		"PA": {ID: 3, Country: "Panama", Name: "Liga Muslim dunia"},
		"PG": {ID: 3, Country: "Papua Nugini", Name: "Liga Muslim dunia"},
		"PY": {ID: 3, Country: "Paraguay", Name: "Liga Muslim dunia"},
		"PE": {ID: 3, Country: "Peru", Name: "Liga Muslim dunia"},
		"PL": {ID: 3, Country: "Polandia", Name: "Liga Muslim dunia"},
		"PF": {ID: 3, Country: "Polinesia Prancis", Name: "Liga Muslim dunia"},
		"PT": {ID: 3, Country: "Portugal", Name: "Liga Muslim dunia"},
		"FR": {ID: 11, Country: "Prancis", Name: "Union des organisasi Islamiques de France"},
		"PR": {ID: 3, Country: "Puerto Riko", Name: "Liga Muslim dunia"},
		"BV": {ID: 3, Country: "Pulau Bouvet", Name: "Liga Muslim dunia"},
		"HM": {ID: 3, Country: "Pulau Heard dan Kepulauan McDonald", Name: "Liga Muslim dunia"},
		"CX": {ID: 3, Country: "Pulau Natal", Name: "Liga Muslim dunia"},
		"NF": {ID: 3, Country: "Pulau Norfolk", Name: "Liga Muslim dunia"},
		"QA": {ID: 4, Country: "Qatar", Name: "Umm Al Qura University, Mekkah"},
		"XK": {ID: 3, Country: "Republic of Kosovo", Name: "Liga Muslim dunia"},
		"CF": {ID: 5, Country: "Republik Afrika Tengah", Name: "Dinas geologi Mesir"},
		"CZ": {ID: 3, Country: "Republik Ceko", Name: "Liga Muslim dunia"},
		"CD": {ID: 5, Country: "Republik Demokratik Kongo", Name: "Dinas geologi Mesir"},
		"DO": {ID: 3, Country: "Republik Dominika", Name: "Liga Muslim dunia"},
		"RE": {ID: 5, Country: "Reunion", Name: "Dinas geologi Mesir"},
		"RO": {ID: 3, Country: "Romania", Name: "Liga Muslim dunia"},
		"RU": {ID: 3, Country: "Rusia", Name: "Liga Muslim dunia"},
		"RW": {ID: 5, Country: "Rwanda", Name: "Dinas geologi Mesir"},
		"EH": {ID: 3, Country: "Sahara Barat", Name: "Liga Muslim dunia"},
		"BL": {ID: 3, Country: "Saint Barthelemy", Name: "Liga Muslim dunia"},
		"SH": {ID: 5, Country: "Saint Helena", Name: "Dinas geologi Mesir"},
		"KN": {ID: 3, Country: "Saint Kitts dan Nevis", Name: "Liga Muslim dunia"},
		"LC": {ID: 3, Country: "Saint Lucia", Name: "Liga Muslim dunia"},
		"MF": {ID: 3, Country: "Saint Martin", Name: "Liga Muslim dunia"},
		"PM": {ID: 3, Country: "Saint Pierre dan Miquelon", Name: "Liga Muslim dunia"},
		"VC": {ID: 3, Country: "Saint Vincent dan Grenadines", Name: "Liga Muslim dunia"},
		"WS": {ID: 3, Country: "Samoa", Name: "Liga Muslim dunia"},
		"AS": {ID: 3, Country: "Samoa Amerika", Name: "Liga Muslim dunia"},
		"SM": {ID: 3, Country: "San Marino", Name: "Liga Muslim dunia"},
		"ST": {ID: 5, Country: "Sao Tome dan Príncipe", Name: "Dinas geologi Mesir"},
		"NZ": {ID: 3, Country: "Selandia Baru", Name: "Liga Muslim dunia"},
		"TF": {ID: 3, Country: "Selatan Perancis dan Daratan Antartika", Name: "Liga Muslim dunia"},
		"SN": {ID: 5, Country: "Senegal", Name: "Dinas geologi Mesir"},
		"RS": {ID: 3, Country: "Serbia", Name: "Liga Muslim dunia"},
		"SC": {ID: 5, Country: "Seychelles", Name: "Dinas geologi Mesir"},
		"SL": {ID: 5, Country: "Sierra Leone", Name: "Dinas geologi Mesir"},
		"SG": {ID: 10, Country: "Singapura", Name: "Majlis Ugama Islam Singapura"},
		"SX": {ID: 3, Country: "Sint Maarten", Name: "Liga Muslim dunia"},
		"CY": {ID: 3, Country: "Siprus", Name: "Liga Muslim dunia"},
		"SK": {ID: 3, Country: "Slovakia", Name: "Liga Muslim dunia"},
		"SI": {ID: 3, Country: "Slovenia", Name: "Liga Muslim dunia"},
		"SO": {ID: 5, Country: "Somalia", Name: "Dinas geologi Mesir"},
		"SS": {ID: 5, Country: "South Sudan", Name: "Dinas geologi Mesir"},
		"ES": {ID: 3, Country: "Spanyol", Name: "Liga Muslim dunia"},
		"LK": {ID: 3, Country: "Sri Lanka", Name: "Liga Muslim dunia"},
		"SD": {ID: 3, Country: "Sudan", Name: "Liga Muslim dunia"},
		"SY": {ID: 3, Country: "Suriah", Name: "Liga Muslim dunia"},
		"SR": {ID: 3, Country: "Suriname", Name: "Liga Muslim dunia"},
		"SJ": {ID: 3, Country: "Svalbard", Name: "Liga Muslim dunia"},
		"SZ": {ID: 5, Country: "Swaziland", Name: "Dinas geologi Mesir"},
		"SE": {ID: 3, Country: "Swedia", Name: "Liga Muslim dunia"},
		"CH": {ID: 3, Country: "Swiss", Name: "Liga Muslim dunia"},
		"VA": {ID: 3, Country: "Tahta Suci (Vatikan)", Name: "Liga Muslim dunia"},
		"TW": {ID: 3, Country: "Taiwan", Name: "Liga Muslim dunia"},
		"TJ": {ID: 3, Country: "Tajikistan", Name: "Liga Muslim dunia"},
		"GL": {ID: 3, Country: "Tanah Hijau", Name: "Liga Muslim dunia"},
		"CV": {ID: 5, Country: "Tanjung Verde", Name: "Dinas geologi Mesir"},
		"TZ": {ID: 5, Country: "Tanzania", Name: "Dinas geologi Mesir"},
		"IO": {ID: 3, Country: "Teritori Inggris di Samudra Hindia", Name: "Liga Muslim dunia"},
		"TH": {ID: 3, Country: "Thailand", Name: "Liga Muslim dunia"},
		"TL": {ID: 3, Country: "Timor-Leste", Name: "Liga Muslim dunia"},
		"TG": {ID: 5, Country: "Togo", Name: "Dinas geologi Mesir"},
		"TK": {ID: 3, Country: "Tokelau", Name: "Liga Muslim dunia"},
		"TO": {ID: 3, Country: "Tonga", Name: "Liga Muslim dunia"},
		"TT": {ID: 3, Country: "Trinidad dan Tobago", Name: "Liga Muslim dunia"},
		"TN": {ID: 5, Country: "Tunisia", Name: "Dinas geologi Mesir"},
		"TR": {ID: 12, Country: "Turki", Name: "Turki"},
		"TM": {ID: 3, Country: "Turkmenistan", Name: "Liga Muslim dunia"},
		"TV": {ID: 3, Country: "Tuvalu", Name: "Liga Muslim dunia"},
		"UG": {ID: 5, Country: "Uganda", Name: "Dinas geologi Mesir"},
		"UA": {ID: 3, Country: "Ukraina", Name: "Liga Muslim dunia"},
		"AE": {ID: 4, Country: "Uni Emirat Arab", Name: "Umm Al Qura University, Mekkah"},
		"UM": {ID: 3, Country: "United States Minor Outlying Islands", Name: "Liga Muslim dunia"},
		"UY": {ID: 3, Country: "Uruguay", Name: "Liga Muslim dunia"},
		"UZ": {ID: 3, Country: "Uzbekistan", Name: "Liga Muslim dunia"},
		"VU": {ID: 3, Country: "Vanuatu", Name: "Liga Muslim dunia"},
		"VE": {ID: 3, Country: "Venezuela", Name: "Liga Muslim dunia"},
		"VN": {ID: 3, Country: "Vietnam", Name: "Liga Muslim dunia"},
		"WF": {ID: 3, Country: "Wallis dan Futuna", Name: "Liga Muslim dunia"},
		"YE": {ID: 4, Country: "Yaman", Name: "Umm Al Qura University, Mekkah"},
		"JO": {ID: 3, Country: "Yordania", Name: "Liga Muslim dunia"},
		"GR": {ID: 3, Country: "Yunani", Name: "Liga Muslim dunia"},
		"ZM": {ID: 5, Country: "Zambia", Name: "Dinas geologi Mesir"},
		"ZW": {ID: 5, Country: "Zimbabwe", Name: "Dinas geologi Mesir"},
	}
)
